// THIS IS AN AUTOGENERATED FILE. If something is wrong, update ./scripts/run_codegen.js, not this file.
export interface IntrinsicElements {
    // HTML Elements
    a: JsxAElementProps
    abbr: JsxCommonHtmlProps
    address: JsxCommonHtmlProps
    area: JsxAreaElementProps
    article: JsxCommonHtmlProps
    aside: JsxCommonHtmlProps
    audio: JsxAudioElementProps
    b: JsxCommonHtmlProps
    base: JsxBaseElementProps
    bdi: JsxCommonHtmlProps
    bdo: JsxCommonHtmlProps
    blockquote: JsxBlockquoteElementProps
    body: JsxBodyElementProps
    br: JsxBrElementProps
    button: JsxButtonElementProps
    canvas: JsxCanvasElementProps
    caption: JsxCaptionElementProps
    cite: JsxCommonHtmlProps
    code: JsxCommonHtmlProps
    col: JsxColElementProps
    colgroup: JsxColgroupElementProps
    data: JsxDataElementProps
    datalist: JsxCommonHtmlProps
    dd: JsxCommonHtmlProps
    del: JsxDelElementProps
    details: JsxDetailsElementProps
    dfn: JsxCommonHtmlProps
    dialog: JsxCommonHtmlProps
    dir: JsxDirElementProps
    div: JsxDivElementProps
    dl: JsxDlElementProps
    dt: JsxCommonHtmlProps
    em: JsxCommonHtmlProps
    embed: JsxEmbedElementProps
    fieldset: JsxFieldsetElementProps
    figcaption: JsxCommonHtmlProps
    figure: JsxCommonHtmlProps
    font: JsxFontElementProps
    footer: JsxCommonHtmlProps
    form: JsxFormElementProps
    frame: JsxFrameElementProps
    frameset: JsxFramesetElementProps
    h1: JsxH1ElementProps
    h2: JsxH2ElementProps
    h3: JsxH3ElementProps
    h4: JsxH4ElementProps
    h5: JsxH5ElementProps
    h6: JsxH6ElementProps
    head: JsxCommonHtmlProps
    header: JsxCommonHtmlProps
    hgroup: JsxCommonHtmlProps
    hr: JsxHrElementProps
    html: JsxHtmlElementProps
    i: JsxCommonHtmlProps
    iframe: JsxIframeElementProps
    img: JsxImgElementProps
    input: JsxInputElementProps
    ins: JsxInsElementProps
    kbd: JsxCommonHtmlProps
    label: JsxLabelElementProps
    legend: JsxLegendElementProps
    li: JsxLiElementProps
    link: JsxLinkElementProps
    main: JsxCommonHtmlProps
    map: JsxMapElementProps
    mark: JsxCommonHtmlProps
    marquee: JsxMarqueeElementProps
    menu: JsxMenuElementProps
    meta: JsxMetaElementProps
    meter: JsxMeterElementProps
    nav: JsxCommonHtmlProps
    noscript: JsxCommonHtmlProps
    object: JsxObjectElementProps
    ol: JsxOlElementProps
    optgroup: JsxOptgroupElementProps
    option: JsxOptionElementProps
    output: JsxOutputElementProps
    p: JsxPElementProps
    param: JsxParamElementProps
    picture: JsxCommonHtmlProps
    pre: JsxPreElementProps
    progress: JsxProgressElementProps
    q: JsxQElementProps
    rp: JsxCommonHtmlProps
    rt: JsxCommonHtmlProps
    ruby: JsxCommonHtmlProps
    s: JsxCommonHtmlProps
    samp: JsxCommonHtmlProps
    script: JsxScriptElementProps
    section: JsxCommonHtmlProps
    select: JsxSelectElementProps
    slot: JsxSlotElementProps
    small: JsxCommonHtmlProps
    source: JsxSourceElementProps
    span: JsxCommonHtmlProps
    strong: JsxCommonHtmlProps
    style: JsxStyleElementProps
    sub: JsxCommonHtmlProps
    summary: JsxCommonHtmlProps
    sup: JsxCommonHtmlProps
    table: JsxTableElementProps
    tbody: JsxTbodyElementProps
    td: JsxTdElementProps
    template: JsxCommonHtmlProps
    textarea: JsxTextareaElementProps
    tfoot: JsxTfootElementProps
    th: JsxThElementProps
    thead: JsxTheadElementProps
    time: JsxTimeElementProps
    title: JsxTitleElementProps
    tr: JsxTrElementProps
    track: JsxTrackElementProps
    u: JsxCommonHtmlProps
    ul: JsxUlElementProps
    var: JsxCommonHtmlProps
    video: JsxVideoElementProps
    wbr: JsxCommonHtmlProps

    // SVG Elements
    animate: JsxAnimateElementProps
    animateMotion: JsxAnimateMotionElementProps
    animateTransform: JsxAnimateTransformElementProps
    circle: JsxCircleElementProps
    clipPath: JsxClipPathElementProps
    defs: JsxDefsElementProps
    desc: JsxCommonSvgProps
    ellipse: JsxEllipseElementProps
    feBlend: JsxFeBlendElementProps
    feColorMatrix: JsxFeColorMatrixElementProps
    feComponentTransfer: JsxFeComponentTransferElementProps
    feComposite: JsxFeCompositeElementProps
    feConvolveMatrix: JsxFeConvolveMatrixElementProps
    feDiffuseLighting: JsxFeDiffuseLightingElementProps
    feDisplacementMap: JsxFeDisplacementMapElementProps
    feDistantLight: JsxFeDistantLightElementProps
    feDropShadow: JsxFeDropShadowElementProps
    feFlood: JsxFeFloodElementProps
    feFuncA: JsxFeFuncAElementProps
    feFuncB: JsxFeFuncBElementProps
    feFuncG: JsxFeFuncGElementProps
    feFuncR: JsxFeFuncRElementProps
    feGaussianBlur: JsxFeGaussianBlurElementProps
    feImage: JsxFeImageElementProps
    feMerge: JsxFeMergeElementProps
    feMergeNode: JsxFeMergeNodeElementProps
    feMorphology: JsxFeMorphologyElementProps
    feOffset: JsxFeOffsetElementProps
    fePointLight: JsxFePointLightElementProps
    feSpecularLighting: JsxFeSpecularLightingElementProps
    feSpotLight: JsxFeSpotLightElementProps
    feTile: JsxFeTileElementProps
    feTurbulence: JsxFeTurbulenceElementProps
    filter: JsxFilterElementProps
    foreignObject: JsxForeignObjectElementProps
    g: JsxGElementProps
    image: JsxImageElementProps
    line: JsxLineElementProps
    linearGradient: JsxLinearGradientElementProps
    marker: JsxMarkerElementProps
    mask: JsxMaskElementProps
    metadata: JsxCommonSvgProps
    mpath: JsxMpathElementProps
    path: JsxPathElementProps
    pattern: JsxPatternElementProps
    polygon: JsxPolygonElementProps
    polyline: JsxPolylineElementProps
    radialGradient: JsxRadialGradientElementProps
    rect: JsxRectElementProps
    set: JsxSetElementProps
    stop: JsxStopElementProps
    svg: JsxSvgElementProps
    switch: JsxSwitchElementProps
    symbol: JsxSymbolElementProps
    text: JsxTextElementProps
    textPath: JsxTextPathElementProps
    tspan: JsxTspanElementProps
    use: JsxUseElementProps
    view: JsxViewElementProps
}

export const JsxFragment = Symbol();

export type JsxComponent<P> = (props: P) => JsxElement | null | undefined;

export interface JsxElement {
    tag: typeof JsxFragment | string | JsxComponent<any>;
    props: object | null;
    children: JsxChildren[];
}

export type JsxChildren =
    | JsxElement
    | string
    | number
    | null
    | undefined
    | JsxChildren[];

export interface JsxCommonHtmlProps {
    accessKey?: string
    accessKeyLabel?: string
    autocapitalize?: string
    baseURI?: string
    children?: JsxChildren
    class?: string
    classList?: string
    clientHeight?: number
    clientLeft?: number
    clientTop?: number
    clientWidth?: number
    contentEditable?: string
    dir?: string
    draggable?: boolean
    enterKeyHint?: string
    hidden?: boolean
    id?: string
    inputMode?: string
    isConnected?: boolean
    isContentEditable?: boolean
    lang?: string
    localName?: string
    namespaceURI?: string
    nodeName?: string
    nodeType?: number
    nodeValue?: string
    nonce?: string
    offsetHeight?: number
    offsetLeft?: number
    offsetTop?: number
    offsetWidth?: number
    ownerDocument?: Document
    part?: string
    prefix?: string
    scrollHeight?: number
    scrollLeft?: number
    scrollTop?: number
    scrollWidth?: number
    slot?: string
    spellcheck?: boolean
    tabIndex?: number
    tagName?: string
    title?: string
    translate?: boolean
}

export interface JsxCommonSvgProps {
    baseURI?: string
    children?: JsxChildren
    class?: any
    classList?: string
    clientHeight?: number
    clientLeft?: number
    clientTop?: number
    clientWidth?: number
    d?: string
    fill?: string
    id?: string
    isConnected?: boolean
    localName?: string
    namespaceURI?: string
    nodeName?: string
    nodeType?: number
    nodeValue?: string
    nonce?: string
    ownerDocument?: Document
    part?: string
    prefix?: string
    scrollHeight?: number
    scrollLeft?: number
    scrollTop?: number
    scrollWidth?: number
    slot?: string
    stroke?: string
    tabIndex?: number
    tagName?: string
    xmlns?: string
}

export interface JsxAElementProps extends JsxCommonHtmlProps {
    charset?: string
    coords?: string
    download?: string
    hash?: string
    host?: string
    hostname?: string
    href?: string
    hreflang?: string
    name?: string
    origin?: string
    password?: string
    pathname?: string
    ping?: string
    port?: string
    protocol?: string
    referrerPolicy?: string
    rel?: string
    relList?: string
    rev?: string
    search?: string
    shape?: string
    target?: string
    text?: string
    type?: string
    username?: string
}

export interface JsxAreaElementProps extends JsxCommonHtmlProps {
    alt?: string
    coords?: string
    download?: string
    hash?: string
    host?: string
    hostname?: string
    href?: string
    noHref?: boolean
    origin?: string
    password?: string
    pathname?: string
    ping?: string
    port?: string
    protocol?: string
    referrerPolicy?: string
    rel?: string
    relList?: string
    search?: string
    shape?: string
    target?: string
    username?: string
}

export interface JsxAudioElementProps extends JsxCommonHtmlProps {
    autoplay?: boolean
    controls?: boolean
    crossOrigin?: string
    currentSrc?: string
    currentTime?: number
    defaultMuted?: boolean
    defaultPlaybackRate?: number
    disableRemotePlayback?: boolean
    duration?: number
    ended?: boolean
    loop?: boolean
    muted?: boolean
    networkState?: number
    paused?: boolean
    playbackRate?: number
    preload?: string
    readyState?: number
    seeking?: boolean
    src?: string
    srcObject?: string
    volume?: number
}

export interface JsxBaseElementProps extends JsxCommonHtmlProps {
    href?: string
    target?: string
}

export interface JsxBlockquoteElementProps extends JsxCommonHtmlProps {
    cite?: string
}

export interface JsxBodyElementProps extends JsxCommonHtmlProps {
    aLink?: string
    background?: string
    bgColor?: string
    link?: string
    text?: string
    vLink?: string
}

export interface JsxBrElementProps extends JsxCommonHtmlProps {
    clear?: string
}

export interface JsxButtonElementProps extends JsxCommonHtmlProps {
    disabled?: boolean
    formAction?: string
    formEnctype?: string
    formMethod?: string
    formNoValidate?: boolean
    formTarget?: string
    name?: string
    type?: string
    validationMessage?: string
    value?: string
    willValidate?: boolean
}

export interface JsxCanvasElementProps extends JsxCommonHtmlProps {
    height?: number
    width?: number
}

export interface JsxCaptionElementProps extends JsxCommonHtmlProps {
    align?: string
}

export interface JsxColElementProps extends JsxCommonHtmlProps {
    align?: string
    ch?: string
    chOff?: string
    span?: number
    vAlign?: string
    width?: string
}

export interface JsxColgroupElementProps extends JsxCommonHtmlProps {
    align?: string
    ch?: string
    chOff?: string
    span?: number
    vAlign?: string
    width?: string
}

export interface JsxDataElementProps extends JsxCommonHtmlProps {
    value?: string
}

export interface JsxDelElementProps extends JsxCommonHtmlProps {
    cite?: string
    dateTime?: string
}

export interface JsxDetailsElementProps extends JsxCommonHtmlProps {
    open?: boolean
}

export interface JsxDirElementProps extends JsxCommonHtmlProps {
    compact?: boolean
}

export interface JsxDivElementProps extends JsxCommonHtmlProps {
    align?: string
}

export interface JsxDlElementProps extends JsxCommonHtmlProps {
    compact?: boolean
}

export interface JsxEmbedElementProps extends JsxCommonHtmlProps {
    align?: string
    height?: string
    name?: string
    src?: string
    type?: string
    width?: string
}

export interface JsxFieldsetElementProps extends JsxCommonHtmlProps {
    disabled?: boolean
    name?: string
    type?: string
    validationMessage?: string
    willValidate?: boolean
}

export interface JsxFontElementProps extends JsxCommonHtmlProps {
    color?: string
    face?: string
    size?: string
}

export interface JsxFormElementProps extends JsxCommonHtmlProps {
    acceptCharset?: string
    action?: string
    autocomplete?: string
    encoding?: string
    enctype?: string
    length?: number
    method?: string
    name?: string
    noValidate?: boolean
    target?: string
}

export interface JsxFrameElementProps extends JsxCommonHtmlProps {
    contentDocument?: Document
    contentWindow?: Window
    frameBorder?: string
    longDesc?: string
    marginHeight?: string
    marginWidth?: string
    name?: string
    noResize?: boolean
    scrolling?: string
    src?: string
}

export interface JsxFramesetElementProps extends JsxCommonHtmlProps {
    cols?: string
}

export interface JsxH1ElementProps extends JsxCommonHtmlProps {
    align?: string
}

export interface JsxH2ElementProps extends JsxCommonHtmlProps {
    align?: string
}

export interface JsxH3ElementProps extends JsxCommonHtmlProps {
    align?: string
}

export interface JsxH4ElementProps extends JsxCommonHtmlProps {
    align?: string
}

export interface JsxH5ElementProps extends JsxCommonHtmlProps {
    align?: string
}

export interface JsxH6ElementProps extends JsxCommonHtmlProps {
    align?: string
}

export interface JsxHrElementProps extends JsxCommonHtmlProps {
    align?: string
    color?: string
    noShade?: boolean
    size?: string
    width?: string
}

export interface JsxHtmlElementProps extends JsxCommonHtmlProps {
    version?: string
}

export interface JsxIframeElementProps extends JsxCommonHtmlProps {
    align?: string
    allow?: string
    allowFullscreen?: boolean
    contentDocument?: Document
    contentWindow?: Window
    frameBorder?: string
    height?: string
    longDesc?: string
    marginHeight?: string
    marginWidth?: string
    name?: string
    referrerPolicy?: string
    sandbox?: string
    scrolling?: string
    src?: string
    srcdoc?: string
    width?: string
}

export interface JsxImgElementProps extends JsxCommonHtmlProps {
    align?: string
    alt?: string
    border?: string
    complete?: boolean
    crossOrigin?: string
    currentSrc?: string
    decoding?: "async" | "sync" | "auto"
    height?: number
    hspace?: number
    isMap?: boolean
    loading?: string
    longDesc?: string
    lowsrc?: string
    name?: string
    naturalHeight?: number
    naturalWidth?: number
    referrerPolicy?: string
    sizes?: string
    src?: string
    srcset?: string
    useMap?: string
    vspace?: number
    width?: number
    x?: number
    y?: number
}

export interface JsxInputElementProps extends JsxCommonHtmlProps {
    accept?: string
    align?: string
    alt?: string
    autocomplete?: string
    capture?: string
    checked?: boolean
    defaultChecked?: boolean
    defaultValue?: string
    dirName?: string
    disabled?: boolean
    formAction?: string
    formEnctype?: string
    formMethod?: string
    formNoValidate?: boolean
    formTarget?: string
    height?: number
    indeterminate?: boolean
    max?: string
    maxLength?: number
    min?: string
    minLength?: number
    multiple?: boolean
    name?: string
    pattern?: string
    placeholder?: string
    readOnly?: boolean
    required?: boolean
    selectionDirection?: "forward" | "backward" | "none"
    selectionEnd?: number
    selectionStart?: number
    size?: number
    src?: string
    step?: string
    type?: string
    useMap?: string
    validationMessage?: string
    value?: string
    valueAsDate?: Date
    valueAsNumber?: number
    webkitdirectory?: boolean
    width?: number
    willValidate?: boolean
}

export interface JsxInsElementProps extends JsxCommonHtmlProps {
    cite?: string
    dateTime?: string
}

export interface JsxLabelElementProps extends JsxCommonHtmlProps {
    for?: string
}

export interface JsxLegendElementProps extends JsxCommonHtmlProps {
    align?: string
}

export interface JsxLiElementProps extends JsxCommonHtmlProps {
    type?: string
    value?: number
}

export interface JsxLinkElementProps extends JsxCommonHtmlProps {
    as?: string
    charset?: string
    crossOrigin?: string
    disabled?: boolean
    href?: string
    hreflang?: string
    imageSizes?: string
    imageSrcset?: string
    integrity?: string
    media?: string
    referrerPolicy?: string
    rel?: string
    relList?: string
    rev?: string
    sizes?: string
    target?: string
    type?: string
}

export interface JsxMapElementProps extends JsxCommonHtmlProps {
    areas?: JsxChildren
    name?: string
}

export interface JsxMarqueeElementProps extends JsxCommonHtmlProps {
    behavior?: string
    bgColor?: string
    direction?: string
    height?: string
    hspace?: number
    loop?: number
    scrollAmount?: number
    scrollDelay?: number
    trueSpeed?: boolean
    vspace?: number
    width?: string
}

export interface JsxMenuElementProps extends JsxCommonHtmlProps {
    compact?: boolean
}

export interface JsxMetaElementProps extends JsxCommonHtmlProps {
    "http-equiv"?: string
    charSet?: string
    content?: string
    name?: string
    scheme?: string
}

export interface JsxMeterElementProps extends JsxCommonHtmlProps {
    high?: number
    low?: number
    max?: number
    min?: number
    optimum?: number
    value?: number
}

export interface JsxObjectElementProps extends JsxCommonHtmlProps {
    align?: string
    archive?: string
    border?: string
    code?: string
    codeBase?: string
    codeType?: string
    contentDocument?: Document
    contentWindow?: Window
    data?: string
    declare?: boolean
    height?: string
    hspace?: number
    name?: string
    standby?: string
    type?: string
    useMap?: string
    validationMessage?: string
    vspace?: number
    width?: string
    willValidate?: boolean
}

export interface JsxOlElementProps extends JsxCommonHtmlProps {
    compact?: boolean
    reversed?: boolean
    start?: number
    type?: string
}

export interface JsxOptgroupElementProps extends JsxCommonHtmlProps {
    disabled?: boolean
    label?: string
}

export interface JsxOptionElementProps extends JsxCommonHtmlProps {
    defaultSelected?: boolean
    disabled?: boolean
    index?: number
    label?: string
    selected?: boolean
    text?: string
    value?: string
}

export interface JsxOutputElementProps extends JsxCommonHtmlProps {
    defaultValue?: string
    for?: string
    name?: string
    type?: string
    validationMessage?: string
    value?: string
    willValidate?: boolean
}

export interface JsxPElementProps extends JsxCommonHtmlProps {
    align?: string
}

export interface JsxParamElementProps extends JsxCommonHtmlProps {
    name?: string
    type?: string
    value?: string
    valueType?: string
}

export interface JsxPreElementProps extends JsxCommonHtmlProps {
    width?: number
}

export interface JsxProgressElementProps extends JsxCommonHtmlProps {
    max?: number
    position?: number
    value?: number
}

export interface JsxQElementProps extends JsxCommonHtmlProps {
    cite?: string
}

export interface JsxScriptElementProps extends JsxCommonHtmlProps {
    async?: boolean
    charset?: string
    crossOrigin?: string
    defer?: boolean
    event?: string
    for?: string
    integrity?: string
    noModule?: boolean
    referrerPolicy?: string
    src?: string
    text?: string
    type?: string
}

export interface JsxSelectElementProps extends JsxCommonHtmlProps {
    autocomplete?: string
    disabled?: boolean
    length?: number
    multiple?: boolean
    name?: string
    required?: boolean
    selectedIndex?: number
    size?: number
    type?: string
    validationMessage?: string
    value?: string
    willValidate?: boolean
}

export interface JsxSlotElementProps extends JsxCommonHtmlProps {
    name?: string
}

export interface JsxSourceElementProps extends JsxCommonHtmlProps {
    media?: string
    sizes?: string
    src?: string
    srcset?: string
    type?: string
}

export interface JsxStyleElementProps extends JsxCommonHtmlProps {
    media?: string
    type?: string
}

export interface JsxTableElementProps extends JsxCommonHtmlProps {
    align?: string
    bgColor?: string
    border?: string
    cellPadding?: string
    cellSpacing?: string
    frame?: string
    rules?: string
    summary?: string
    width?: string
}

export interface JsxTbodyElementProps extends JsxCommonHtmlProps {
    align?: string
    ch?: string
    chOff?: string
    vAlign?: string
}

export interface JsxTdElementProps extends JsxCommonHtmlProps {
    abbr?: string
    align?: string
    axis?: string
    bgColor?: string
    cellIndex?: number
    ch?: string
    chOff?: string
    colSpan?: number
    headers?: string
    height?: string
    noWrap?: boolean
    rowSpan?: number
    scope?: string
    vAlign?: string
    width?: string
}

export interface JsxTextareaElementProps extends JsxCommonHtmlProps {
    autocomplete?: string
    cols?: number
    defaultValue?: string
    dirName?: string
    disabled?: boolean
    maxLength?: number
    minLength?: number
    name?: string
    placeholder?: string
    readOnly?: boolean
    required?: boolean
    selectionDirection?: "forward" | "backward" | "none"
    selectionEnd?: number
    selectionStart?: number
    textLength?: number
    type?: string
    validationMessage?: string
    value?: string
    willValidate?: boolean
    wrap?: string
}

export interface JsxTfootElementProps extends JsxCommonHtmlProps {
    align?: string
    ch?: string
    chOff?: string
    vAlign?: string
}

export interface JsxThElementProps extends JsxCommonHtmlProps {
    abbr?: string
    align?: string
    axis?: string
    bgColor?: string
    cellIndex?: number
    ch?: string
    chOff?: string
    colSpan?: number
    headers?: string
    height?: string
    noWrap?: boolean
    rowSpan?: number
    scope?: string
    vAlign?: string
    width?: string
}

export interface JsxTheadElementProps extends JsxCommonHtmlProps {
    align?: string
    ch?: string
    chOff?: string
    vAlign?: string
}

export interface JsxTimeElementProps extends JsxCommonHtmlProps {
    dateTime?: string
}

export interface JsxTitleElementProps extends JsxCommonHtmlProps {
    text?: string
}

export interface JsxTrElementProps extends JsxCommonHtmlProps {
    align?: string
    bgColor?: string
    ch?: string
    chOff?: string
    rowIndex?: number
    sectionRowIndex?: number
    vAlign?: string
}

export interface JsxTrackElementProps extends JsxCommonHtmlProps {
    default?: boolean
    kind?: string
    label?: string
    readyState?: number
    src?: string
    srclang?: string
}

export interface JsxUlElementProps extends JsxCommonHtmlProps {
    compact?: boolean
    type?: string
}

export interface JsxVideoElementProps extends JsxCommonHtmlProps {
    autoplay?: boolean
    controls?: boolean
    crossOrigin?: string
    currentSrc?: string
    currentTime?: number
    defaultMuted?: boolean
    defaultPlaybackRate?: number
    disablePictureInPicture?: boolean
    disableRemotePlayback?: boolean
    duration?: number
    ended?: boolean
    height?: number
    loop?: boolean
    muted?: boolean
    networkState?: number
    paused?: boolean
    playbackRate?: number
    playsInline?: boolean
    poster?: string
    preload?: string
    readyState?: number
    seeking?: boolean
    src?: string
    srcObject?: string
    videoHeight?: number
    videoWidth?: number
    volume?: number
    width?: number
}

export interface JsxAnimateElementProps extends JsxCommonSvgProps {
    requiredExtensions?: string
    systemLanguage?: string
}

export interface JsxAnimateMotionElementProps extends JsxCommonSvgProps {
    requiredExtensions?: string
    systemLanguage?: string
}

export interface JsxAnimateTransformElementProps extends JsxCommonSvgProps {
    requiredExtensions?: string
    systemLanguage?: string
}

export interface JsxCircleElementProps extends JsxCommonSvgProps {
    cx?: string | number
    cy?: string | number
    pathLength?: string | number
    r?: string | number
    requiredExtensions?: string
    systemLanguage?: string
    transform?: string
}

export interface JsxClipPathElementProps extends JsxCommonSvgProps {
    clipPathUnits?: string
    transform?: string
}

export interface JsxDefsElementProps extends JsxCommonSvgProps {
    requiredExtensions?: string
    systemLanguage?: string
    transform?: string
}

export interface JsxEllipseElementProps extends JsxCommonSvgProps {
    cx?: string | number
    cy?: string | number
    pathLength?: string | number
    requiredExtensions?: string
    rx?: string | number
    ry?: string | number
    systemLanguage?: string
    transform?: string
}

export interface JsxFeBlendElementProps extends JsxCommonSvgProps {
    height?: string | number
    in1?: string
    in2?: string
    mode?: string
    result?: string
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxFeColorMatrixElementProps extends JsxCommonSvgProps {
    height?: string | number
    in1?: string
    result?: string
    type?: string
    values?: string
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxFeComponentTransferElementProps extends JsxCommonSvgProps {
    height?: string | number
    in1?: string
    result?: string
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxFeCompositeElementProps extends JsxCommonSvgProps {
    height?: string | number
    in1?: string
    in2?: string
    k1?: string | number
    k2?: string | number
    k3?: string | number
    k4?: string | number
    operator?: string
    result?: string
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxFeConvolveMatrixElementProps extends JsxCommonSvgProps {
    bias?: string | number
    divisor?: string | number
    edgeMode?: string
    height?: string | number
    in1?: string
    kernelMatrix?: string
    kernelUnitLengthX?: string | number
    kernelUnitLengthY?: string | number
    orderX?: `${bigint}` | number
    orderY?: `${bigint}` | number
    preserveAlpha?: "true" | "false"
    result?: string
    targetX?: `${bigint}` | number
    targetY?: `${bigint}` | number
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxFeDiffuseLightingElementProps extends JsxCommonSvgProps {
    diffuseConstant?: string | number
    height?: string | number
    in1?: string
    kernelUnitLengthX?: string | number
    kernelUnitLengthY?: string | number
    result?: string
    surfaceScale?: string | number
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxFeDisplacementMapElementProps extends JsxCommonSvgProps {
    height?: string | number
    in1?: string
    in2?: string
    result?: string
    scale?: string | number
    width?: string | number
    x?: string | number
    xChannelSelector?: string
    y?: string | number
    yChannelSelector?: string
}

export interface JsxFeDistantLightElementProps extends JsxCommonSvgProps {
    azimuth?: string | number
    elevation?: string | number
}

export interface JsxFeDropShadowElementProps extends JsxCommonSvgProps {
    dx?: string | number
    dy?: string | number
    height?: string | number
    in1?: string
    result?: string
    stdDeviationX?: string | number
    stdDeviationY?: string | number
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxFeFloodElementProps extends JsxCommonSvgProps {
    height?: string | number
    result?: string
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxFeFuncAElementProps extends JsxCommonSvgProps {
    amplitude?: string | number
    exponent?: string | number
    intercept?: string | number
    offset?: string | number
    slope?: string | number
    tableValues?: string
    type?: string
}

export interface JsxFeFuncBElementProps extends JsxCommonSvgProps {
    amplitude?: string | number
    exponent?: string | number
    intercept?: string | number
    offset?: string | number
    slope?: string | number
    tableValues?: string
    type?: string
}

export interface JsxFeFuncGElementProps extends JsxCommonSvgProps {
    amplitude?: string | number
    exponent?: string | number
    intercept?: string | number
    offset?: string | number
    slope?: string | number
    tableValues?: string
    type?: string
}

export interface JsxFeFuncRElementProps extends JsxCommonSvgProps {
    amplitude?: string | number
    exponent?: string | number
    intercept?: string | number
    offset?: string | number
    slope?: string | number
    tableValues?: string
    type?: string
}

export interface JsxFeGaussianBlurElementProps extends JsxCommonSvgProps {
    height?: string | number
    in1?: string
    result?: string
    stdDeviationX?: string | number
    stdDeviationY?: string | number
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxFeImageElementProps extends JsxCommonSvgProps {
    height?: string | number
    href?: string
    preserveAspectRatio?: string
    result?: string
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxFeMergeElementProps extends JsxCommonSvgProps {
    height?: string | number
    result?: string
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxFeMergeNodeElementProps extends JsxCommonSvgProps {
    in1?: string
}

export interface JsxFeMorphologyElementProps extends JsxCommonSvgProps {
    height?: string | number
    in1?: string
    operator?: string
    radiusX?: string | number
    radiusY?: string | number
    result?: string
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxFeOffsetElementProps extends JsxCommonSvgProps {
    dx?: string | number
    dy?: string | number
    height?: string | number
    in1?: string
    result?: string
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxFePointLightElementProps extends JsxCommonSvgProps {
    x?: string | number
    y?: string | number
    z?: string | number
}

export interface JsxFeSpecularLightingElementProps extends JsxCommonSvgProps {
    height?: string | number
    in1?: string
    kernelUnitLengthX?: string | number
    kernelUnitLengthY?: string | number
    result?: string
    specularConstant?: string | number
    specularExponent?: string | number
    surfaceScale?: string | number
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxFeSpotLightElementProps extends JsxCommonSvgProps {
    limitingConeAngle?: string | number
    pointsAtX?: string | number
    pointsAtY?: string | number
    pointsAtZ?: string | number
    specularExponent?: string | number
    x?: string | number
    y?: string | number
    z?: string | number
}

export interface JsxFeTileElementProps extends JsxCommonSvgProps {
    height?: string | number
    in1?: string
    result?: string
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxFeTurbulenceElementProps extends JsxCommonSvgProps {
    baseFrequencyX?: string | number
    baseFrequencyY?: string | number
    height?: string | number
    numOctaves?: `${bigint}` | number
    result?: string
    seed?: string | number
    stitchTiles?: string
    type?: string
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxFilterElementProps extends JsxCommonSvgProps {
    filterUnits?: string
    height?: string | number
    href?: string
    primitiveUnits?: string
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxForeignObjectElementProps extends JsxCommonSvgProps {
    height?: string | number
    requiredExtensions?: string
    systemLanguage?: string
    transform?: string
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxGElementProps extends JsxCommonSvgProps {
    requiredExtensions?: string
    systemLanguage?: string
    transform?: string
}

export interface JsxImageElementProps extends JsxCommonSvgProps {
    height?: string | number
    href?: string
    preserveAspectRatio?: string
    requiredExtensions?: string
    systemLanguage?: string
    transform?: string
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxLineElementProps extends JsxCommonSvgProps {
    pathLength?: string | number
    requiredExtensions?: string
    systemLanguage?: string
    transform?: string
    x1?: string | number
    x2?: string | number
    y1?: string | number
    y2?: string | number
}

export interface JsxLinearGradientElementProps extends JsxCommonSvgProps {
    gradientTransform?: string
    gradientUnits?: string
    href?: string
    spreadMethod?: string
    x1?: string | number
    x2?: string | number
    y1?: string | number
    y2?: string | number
}

export interface JsxMarkerElementProps extends JsxCommonSvgProps {
    markerHeight?: string | number
    markerUnits?: string
    markerWidth?: string | number
    orientAngle?: string
    orientType?: string
    preserveAspectRatio?: string
    refX?: string | number
    refY?: string | number
    viewBox?: string
}

export interface JsxMaskElementProps extends JsxCommonSvgProps {
    height?: string | number
    maskContentUnits?: string
    maskUnits?: string
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxMpathElementProps extends JsxCommonSvgProps {
    href?: string
}

export interface JsxPathElementProps extends JsxCommonSvgProps {
    pathLength?: string | number
    requiredExtensions?: string
    systemLanguage?: string
    transform?: string
}

export interface JsxPatternElementProps extends JsxCommonSvgProps {
    height?: string | number
    href?: string
    patternContentUnits?: string
    patternTransform?: string
    patternUnits?: string
    preserveAspectRatio?: string
    viewBox?: string
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxPolygonElementProps extends JsxCommonSvgProps {
    animatedPoints?: string
    pathLength?: string | number
    points?: string
    requiredExtensions?: string
    systemLanguage?: string
    transform?: string
}

export interface JsxPolylineElementProps extends JsxCommonSvgProps {
    animatedPoints?: string
    pathLength?: string | number
    points?: string
    requiredExtensions?: string
    systemLanguage?: string
    transform?: string
}

export interface JsxRadialGradientElementProps extends JsxCommonSvgProps {
    cx?: string | number
    cy?: string | number
    fr?: string | number
    fx?: string | number
    fy?: string | number
    gradientTransform?: string
    gradientUnits?: string
    href?: string
    r?: string | number
    spreadMethod?: string
}

export interface JsxRectElementProps extends JsxCommonSvgProps {
    height?: string | number
    pathLength?: string | number
    requiredExtensions?: string
    rx?: string | number
    ry?: string | number
    systemLanguage?: string
    transform?: string
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxSetElementProps extends JsxCommonSvgProps {
    requiredExtensions?: string
    systemLanguage?: string
}

export interface JsxStopElementProps extends JsxCommonSvgProps {
    offset?: string | number
}

export interface JsxSvgElementProps extends JsxCommonSvgProps {
    currentScale?: number
    height?: string | number
    preserveAspectRatio?: string
    requiredExtensions?: string
    systemLanguage?: string
    transform?: string
    viewBox?: string
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxSwitchElementProps extends JsxCommonSvgProps {
    requiredExtensions?: string
    systemLanguage?: string
    transform?: string
}

export interface JsxSymbolElementProps extends JsxCommonSvgProps {
    preserveAspectRatio?: string
    viewBox?: string
}

export interface JsxTextElementProps extends JsxCommonSvgProps {
    dx?: string
    dy?: string
    lengthAdjust?: string
    requiredExtensions?: string
    rotate?: string
    systemLanguage?: string
    textLength?: string | number
    transform?: string
    x?: string
    y?: string
}

export interface JsxTextPathElementProps extends JsxCommonSvgProps {
    href?: string
    lengthAdjust?: string
    method?: string
    requiredExtensions?: string
    spacing?: string
    startOffset?: string | number
    systemLanguage?: string
    textLength?: string | number
    transform?: string
}

export interface JsxTspanElementProps extends JsxCommonSvgProps {
    dx?: string
    dy?: string
    lengthAdjust?: string
    requiredExtensions?: string
    rotate?: string
    systemLanguage?: string
    textLength?: string | number
    transform?: string
    x?: string
    y?: string
}

export interface JsxUseElementProps extends JsxCommonSvgProps {
    height?: string | number
    href?: string
    requiredExtensions?: string
    systemLanguage?: string
    transform?: string
    width?: string | number
    x?: string | number
    y?: string | number
}

export interface JsxViewElementProps extends JsxCommonSvgProps {
    preserveAspectRatio?: string
    viewBox?: string
}
